Project.create(name: "systems check", description: "real super duper mega hard")
Project.create(name: "history essay", description: "real super duper mega easy")
Project.create(name: "sciencey stuff")

User.create(first_name: "Mark", last_name: "Fletcher", email: "fakemail1@fakerino.com")
User.create(first_name: "Bark", last_name: "2letcher", email: "fakemail2@fakerino.com")
User.create(first_name: "Chark", last_name: "3letcher", email: "fakemail3@fakerino.com")
User.create(first_name: "Wark", last_name: "4letcher", email: "fakemail4@fakerino.com")
User.create(first_name: "Dark", last_name: "5letcher", email: "fakemail5@fakerino.com")
User.create(first_name: "Tark", last_name: "6letcher")
User.create(first_name: "Yark", last_name: "7letcher")
User.create(first_name: "Park", last_name: "8letcher")
User.create(first_name: "Jark", last_name: "9letcher")
User.create(first_name: "Quark", last_name: "10letcher")

Team.create(project_id: 1, user_id: 1)
Team.create(project_id: 1, user_id: 2)
Team.create(project_id: 1, user_id: 3)
Team.create(project_id: 1, user_id: 4)
Team.create(project_id: 2, user_id: 5)
Team.create(project_id: 2, user_id: 6)
Team.create(project_id: 2, user_id: 7)
Team.create(project_id: 3, user_id: 8)
Team.create(project_id: 3, user_id: 9)
Team.create(project_id: 3, user_id: 10)

Task.create(name:"write code", project_id: 1, user_id: 1,description: "don't fail", due_date: "2015-12-11")
Task.create(name:"research information", project_id: 2, user_id: 5, description: "use books")
Task.create(name:"mix explosive materials", project_id: 3, user_id: 8, description: "use chemicals")
Task.create(name:"captain safetyman", project_id: 3, user_id: 9, description: "make sure nobody dies while exploding things")
